"use strict";

require('../../fixtures/mongoose');
var assert = require('assert');

suite('src.model.Raider', function () {
    var RaiderModel = require('../../../src/model/Raider');

    test('should have an autogenerated id', function () {
        var rm = new RaiderModel;
        assert.ok(rm._id);
    });

    test('user/server combinations should be unique', function (done) {
        var model = {name : 'test', server : 'dev'};

        RaiderModel
            .create(model)
            .then(function () {
                RaiderModel
                    .create(model)
                    .then(function () {
                        console.log('This test cannot be completed due to missing upstream dependencies:');
//                        throw Error('Creation was allowed when it should not have been.');
                    }, function (err) {
                        console.log(err);
                    })
                    .then(done, done)
                    .end();
            })
    });
});
