"use strict";

var assert = require('assert');
var mongoose = require('mongoose');

suite('src.model.Raider', function () {
    var RaiderModel = require('../../../src/model/Raider');

    test('should have an autogenerated id', function () {
        var rm = new RaiderModel;
        assert.ok(rm._id);
    });

    test('user/server combinations should be unique', function () {
        assert.ok(false, 'This test is not yet defined.');
    })
});
